### ISSUE TITLE
Clarification: Should strings be zero-terminated?

### ISSUE THREAD

**Issue by nickgirardo** [bigbass1997/TASD-Spec#3]
Should Strings be zero-terminated? I.e. should the string "hello" be stored as length 5 or length 6 as "hello\0"? Should parsers be expected to handle both zero-terminated and non zero-terminated strings?

**Comment by bigbass1997** [comment]
A string is a sequence of bytes which form valid UTF-8 characters. They are not necessarily terminated with any special character. The payload or format of the packet the string is contained in will always (in some form) dictate the length of the string. As such, since \0 (aka NUL) is a valid UTF-8 character, it can be found anywhere within the string, and termination isn't required.

`hello` has a length of 5, and `hello\0` has a length of 6.

How parsers behave will depend on what the developer wants and what the programming language is capable of. While string fields will have some intended purpose, the spec doesn't care _what_ is conveyed by the data, as long as it is valid UTF-8.
